apiVersion: v2
name: fluentd-papertrail
description: A Helm chart to deploy fluentd to send to papertrail
type: application
version: 0.1.1
appVersion: 1.2

keywords:
  - fluentd
  - papertrail

home: "https://github.com/mozilla-it/helm-charts"

sources:
  - https://github.com/papertrail
  - https://github.com/fluent/fluentd

maintainers:
  - name: limed
    email: limed@mozilla.com
