apiVersion: v2
name: sentence-collector
description: A Helm chart for Common Voice's Sentence Collector
type: application
version: 0.1.1
keywords:
  - Mozilla
  - common-voice
  - voice
  - sentence-collector
home: https://commonvoice.mozilla.org/sentence-collector
sources:
  - https://github.com/Common-Voice/sentence-collector
maintainers:
  - name: Web SRE Team
    email: it-sre@mozilla.com

dependencies:
- name: mysql
  version: 8.4.2
  condition: mysql.enabled
  repository: https://charts.bitnami.com/bitnami
