apiVersion: v2
name: data-alert-sender
description: Helm Chart for data-alert-sender, a cron job which sends data alerts from stackdriver metrics
version: 0.0.3
appVersion: 0.0.1
keywords:
  - cron
home: "https://github.com/mozilla-it/data-alert-sender"
sources:
  - "https://github.com/mozilla-it/data-alert-sender"
maintainers:
  - name: mozafrank
    email: afrank@mozilla.com
