{{- if .Values.externalSecrets.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ctms.fullname" . }}
spec:
  backendType: secretsManager
  dataFrom:
  - {{ .Values.externalSecrets.secretName }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ctms.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backendType: secretsManager
  dataFrom:
  - {{ .Values.externalSecrets.secretName }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctms.fullname" . }}
data:
  # echo -n "postgres://ctms:defaultpassword@postgres:5432/ctms" | base64 -w 0
  DATABASE_URL: cG9zdGdyZXM6Ly9tZW50b3Jpbmc6ZGVmYXVsdHBhc3N3b3JkQHBvc3RncmVzOjU0MzIvbWVudG9yaW5n
  # echo -n "this-is-not-the-production-value" | base64
  DJANGO_SECRET_KEY: dGhpcy1pcy1ub3QtdGhlLXByb2R1Y3Rpb24tdmFsdWU=
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctms.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  # echo -n "postgres://ctms:defaultpassword@postgres:5432/ctms" | base64 -w 0
  DATABASE_URL: cG9zdGdyZXM6Ly9tZW50b3Jpbmc6ZGVmYXVsdHBhc3N3b3JkQHBvc3RncmVzOjU0MzIvbWVudG9yaW5n
  # echo -n "this-is-not-the-production-value" | base64
  DJANGO_SECRET_KEY: dGhpcy1pcy1ub3QtdGhlLXByb2R1Y3Rpb24tdmFsdWU=
{{- end }}

