cert-manager:
  install: true

configMap:
  data:
    ADMIN_PASSWORD: dumbetherpadpassword
    DB_HOST: etherpad-db-headless
    DB_NAME: etherpad
    DB_PASS: default-non-secure-password
    DB_USER: etherpad
    ETHERPAD_API_KEY: dumberetherpadapikey
    ETHERPAD_SESSION_KEY: dumbetherpadsecretkey

deployment:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

image:
  tag: stg-9922b5f

imagePullSecrets:
  - name: ecr-registry

ingress:
  hosts:
    - host: pad.allizom.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: etherpad
          servicePort: 80
  le:
    name: stage
    issuer_create: false

mysql:
  fullnameOverride: etherpad-db
  install: true
  auth:
    username: etherpad
    database: etherpad
    password: default-non-secure-password
    rootPassword: default-non-secure-root-password
  image:
    tag: 5.7.33
  primary:
    fullname: etherpad
    persistence:
      enabled: false
