apiVersion: v2
name: pastebin
description: A Helm chart for the Mozilla Pastebin (dpaste) application
type: application
version: 0.1.0

keywords:
  - Mozilla
  - dpaste
  - pastebin

home: https://github.com/mozilla-it/pastebin
sources:
  - https://github.com/mozilla-it/pastebin

maintainers:
  - name: Christina Harlow
    email: charlow@mozilla.com

dependencies:
- name: cert-manager
  version: v1.4.0
  condition: cert-manager.install
  repository: https://charts.jetstack.io
- name: mysql
  version: 8.7.1
  condition: mysql.install
  repository: https://charts.bitnami.com/bitnami
