apiVersion: v2
name: pastebin
description: A Helm chart for the Mozilla Pastebin (dpaste) application
type: application
version: 0.1.5

keywords:
  - Mozilla
  - dpaste
  - pastebin

home: https://github.com/mozilla-it/pastebin
sources:
  - https://github.com/mozilla-it/pastebin

maintainers:
  - name: Web SRE Team
    email: it-sre@mozilla.com

dependencies:
- name: cert-manager
  version: 1.4.4
  condition: cert-manager.install
  repository: https://charts.jetstack.io
- name: mysql
  version: 9.2.0
  condition: mysql.install
  repository: https://charts.bitnami.com/bitnami
